# Generated by Django 3.1 on 2020-08-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nasabah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_regis', models.CharField(max_length=120)),
                ('tanggal', models.DateField()),
                ('nama_nasabah', models.CharField(max_length=120)),
                ('pinjaman_ke', models.IntegerField(max_length=10)),
                ('kasbon', models.CharField(max_length=120)),
                ('storting', models.CharField(max_length=120)),
                ('adm', models.CharField(max_length=120)),
                ('drop_an', models.CharField(max_length=120)),
                ('tabungan_in_out', models.CharField(max_length=120)),
                ('bbm', models.CharField(max_length=120)),
                ('service', models.CharField(max_length=120)),
                ('tunai', models.CharField(max_length=120)),
            ],
        ),
    ]
